assetic:
    bundles: ['AppBundle', 'SymfonyIdAdminBundle', 'FOSUserBundle']
    filters:
        cssrewrite:
            apply_to: '\.css$'
        uglifyjs2:
            bin: /usr/local/bin/uglifyjs #change to your path
            apply_to: '\.js$'
        uglifycss:
            bin: /usr/local/bin/uglifycss #change to your path
            apply_to: '\.css$'

mopa_bootstrap:
    form:
        templating:           MopaBootstrapBundle:Form:fields.html.twig
        horizontal:           true
        horizontal_label_class:  col-sm-2 control-label
        horizontal_label_offset_class:  col-sm-offset-2
        horizontal_input_wrapper_class:  col-sm-10
        render_fieldset:      true
        render_collection_item:  true
        show_legend:          true
        show_child_legend:    true
        checkbox_label:       both
        render_optional_text:  true
        render_required_asterisk:  false
        error_type:           ~
        tabs:
            class:                nav nav-tabs
        help_widget:
            popover:
                title:                ~
                content:              ~
                trigger:              hover
                toggle:               popover
                placement:            right
                selector:             ~
        help_label:
            tooltip:
                title:                ~
                text:                 ~
                icon:                 info-sign
                placement:            top
            popover:
                title:                ~
                content:              ~
                text:                 ~
                icon:                 info-sign
                placement:            top
        collection:
            widget_remove_btn:
                attr:
                    class:                btn btn-default
                label:                remove_item
                icon:                 ~
                icon_inverted:        ~
                wrapper_div:
                    class:            form-group
                horizontal_wrapper_div:
                    class:            col-sm-3 col-sm-offset-3
            widget_add_btn:
                attr:
                    class:                btn btn-default
                label:                add_item
                icon:                 ~
                icon_inverted:        ~

    icons:

        # Icon set to use: ['glyphicons','fontawesome','fontawesome4']
        icon_set:             glyphicons

        # Alias for mopa_bootstrap_icon()
        shortcut:             icon
    menu:
        enabled:              false

        # Menu template to use when rendering
        template:             MopaBootstrapBundle:Menu:menu.html.twig
    initializr:
        meta:
            title:                PLATFORMLITE
            description:          PLATFORMLITE
            keywords:             Platform Lite, Twitter Bootstrap, HTML5 Boilerplate
            author_name:          Muhammad Surya Ihsanuddin
            author_url:           https://github.com/ad3n/PlatformLite
            feed_atom:            ~
            feed_rss:             ~
            sitemap:              ~
            nofollow:             false
            noindex:              false
        dns_prefetch:

            # Default:
            - //ajax.googleapis.com
        google:
            wt:                   ~
            analytics:            ~
            extendedanalytics:    false
        diagnostic_mode:      false

    flash:
        mapping:
            # alertType => [flashType1, ..]
            success: [success]
            danger: [error, danger]
            warning: [warning, warn]
            info: [info, notice]

framework:
    translator: { fallbacks: ['%locale%'] }

knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true

knp_menu:
    twig:
        template: knp_menu.html.twig
    templating: false
    default_renderer: twig

fos_user:
    db_driver: '%user_driver%'
    firewall_name: main
    user_class: '%user_class%'

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: '%redis_server%'
    session:
        prefix: '%redis_prefix%'
        client: default
    doctrine:
        metadata_cache:
            client: default
            entity_manager: default
            namespace: "dmc:"
        query_cache:
            client: default
            entity_manager: default
            namespace: "dqc:"
        result_cache:
            client: default
            entity_manager: default
            namespace: "drc:"
        second_level_cache:
            client: default
            entity_manager: default
            namespace: 'dslc:'

doctrine:
    orm:
        metadata_cache_driver:  redis
        query_cache_driver:     redis
        result_cache_driver:    redis
        second_level_cache:
            enabled:            true

symfonyid_admin:
    app_title: 'IHSAN PLATFORM'
    app_short_title: 'SIAB'
    per_page: 10
    identifier: 'id'
    max_records: 1000
    date_time_format: 'd-m-Y'
    menu:
        name: 'symfonyid_menu'
        loader: 'symfonyid.admin.menu.default_menu_loader'
        path: '@AppBundle/Resources/config/menu.yml'
    upload_dir: 'uploads'
    driver: 'orm' #odm or both
    translation_domain: 'AppBundle'
    filters: ['name']
    number_format:
        decimal_precision: 0
        decimal_separator: ','
        thousand_separator: '.'
    user:
        form_class: 'symfonyid.admin.form.user_form'
        model_class: '%user_class%'
        auto_enable: true
        show_fields: ['fullName', 'username', 'email', 'roles', 'enabled']
        grid_columns: ['fullName', 'username', 'email', 'roles', 'enabled']
        profile_fields: ['fullName', 'username', 'email', 'roles', 'enabled']
        filters: ['fullName', 'username']
        password_form: 'symfonyid.admin.form.change_password_form'
    themes:
        dashboard: 'SymfonyIdAdminBundle:Index:index.html.twig'
        profile: 'SymfonyIdAdminBundle:Index:profile.html.twig'
        change_password: 'SymfonyIdAdminBundle:Index:change_password.html.twig'
        new_view: 'SymfonyIdAdminBundle:Crud:new.html.twig'
        bulk_new_view: 'SymfonyIdAdminBundle:Crud:bulk-new.html.twig'
        edit_view: 'SymfonyIdAdminBundle:Crud:new.html.twig'
        show_view: 'SymfonyIdAdminBundle:Crud:show.html.twig'
        list_view: 'SymfonyIdAdminBundle:Crud:list.html.twig'
        pagination: 'SymfonyIdAdminBundle:Layout:pagination.html.twig'